language: java
jdk:
  - oraclejdk8
after_failure: ./print_surefire_reports.sh
env:
  - BUILD="test"
  - BUILD="failsafe:integration-test"
script:
  - set -x; mvn ${BUILD}
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cb192d768f68c8acc006
    on_success: change  
    on_failure: always  
    on_start: false     
